#ifndef GUARD_GLOBAL_CONST_GBA_DUAL_SLOT_H
#define GUARD_GLOBAL_CONST_GBA_DUAL_SLOT_H

#define VAR_GBA_CART_FR  0
#define VAR_GBA_CART_LG  1
#define VAR_GBA_CART_R   2
#define VAR_GBA_CART_S   3
#define VAR_GBA_CART_E   4
#define VAR_GBA_CART_Off 5

#endif //GUARD_GLOBAL_CONST_GBA_DUAL_SLOT_H