gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"

gText_Rowan_Welcome::
	.string "Hello there!\p"
	.string "It's so very nice to meet you!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Rowan.\p"
	.string "However everyone calls me\n"
	.string "the Pokémon Professor.\p"
	.string "$"

gText_Rowan_First_Adventure::
	.string "Before I go any further, is this\n"
	.string "your first adventure?\p"
	.string "If you need advice, I'm certainly\n"
	.string "capable of giving it.\p"
	.string "$"


gText_Rowan_Pokemon::
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "Here, I have a Poké Ball.\p"
	.string "Touch the button on the middle of\n"
	.string "the Poké Ball, if you'd please.\p"
	.string "$"

gText_Rowan_MainSpeech::
	.string "We humans live alongside Pokémon\n"
	.string "as friends.\p"
	.string "At times we play together,\n"
	.string "and at other times we\l"
	.string "work together.\p"
	.string "Some people use their Pokémon\n"
	.string "to battle and develop\l"
	.string "closer bonds with them.\p"
	.string "What do I do?\p"
	.string "I conduct research so that we may\n"
	.string "learn more about Pokémon.\p"
	.string "$"

gText_Rowan_AndYouAre::
	.string "Now, why don't you tell me\n"
	.string "a little bit about yourself?\p"
	.string "$"

gText_Rowan_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Rowan_BoyConfirmation::
	.string "All right, so you're a boy?$"

gText_Rowan_GirlConfirmation::
	.string "All right, so you're a girl?$"

gText_Rowan_WhatsYourName::
	.string "Tell me, what is your name?$"

gText_Rowan_SoItsPlayer::
	.string "Your name is {PLAYER}{KUN}?$"

gText_Rowan_YourePlayer::
	.string "OK...\n"
	.string "So you're {PLAYER}{KUN}?\p"
	.string "A fine name that is!\p"
	.string "$"

gText_Rowan_ThisBoyHere::
	.string "Now, this boy here...\n"
	.string "I believe he's your friend.\p"
	.string "$"

gText_Rowan_WhatsRivalsName::
	.string "What might his name be?$"

gText_Rowan_RivalIsIt::
	.string "{RIVAL}, is it?\n"
	.string "That's your friend's name?\p"
	.string "$"

gText_Rowan_AreYouReady::
	.string "All right, {PLAYER}, the time\n"
	.string "has come.\p"
	.string "Your very own tale of grand\n"
	.string "adventure is about to unfold.\p"
	.string "On your journey, you will meet\n"
	.string "countless Pokémon and people.\p"
	.string "I'm sure that along the way you will\n"
	.string "discover many things, perhaps even\l"
	.string "something about yourself.\p"
	.string "Now, go on, leap into the world of\n"
	.string "Pokémon!\p"
	.string "$"